# Generated by Django 5.0.6 on 2024-08-17 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0001_initial'),
        ('rutas', '0004_alter_ruta_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroinscripcion',
            name='ruta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rutas.ruta'),
        ),
    ]
