# Generated by Django 5.0.6 on 2024-08-17 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0002_registroinscripcion_ruta'),
        ('rutas', '0004_alter_ruta_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroinscripcion',
            name='ruta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rutas.ruta'),
        ),
    ]
