# Generated by Django 5.0.6 on 2024-07-09 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registroContactanos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='clave')),
                ('nombre', models.TextField()),
                ('apellido', models.TextField()),
                ('correo', models.TextField()),
                ('comentario', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'registroContactanos',
                'verbose_name_plural': 'registroContactanos',
                'ordering': ['-created'],
            },
        ),
    ]
