# Generated by Django 5.0.6 on 2024-07-06 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ruta',
            name='duracion',
        ),
        migrations.AddField(
            model_name='ruta',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='rutas/'),
        ),
    ]
