# Generated by Django 5.0.6 on 2024-07-06 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0003_rutarealizada'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruta',
            name='duracion',
            field=models.CharField(default='Desconocida', max_length=100),
        ),
        migrations.AddField(
            model_name='ruta',
            name='fecha',
            field=models.DateField(default='2024-01-01'),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='rutarealizada',
            name='fecha_realizacion',
            field=models.DateField(),
        ),
    ]
