# Generated by Django 5.0.6 on 2024-07-10 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registroInscripcion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='clave')),
                ('nombre', models.CharField(max_length=15)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.IntegerField()),
                ('estado', models.CharField(max_length=15)),
                ('ciudad', models.CharField(max_length=15)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'registroInscripcion',
                'verbose_name_plural': 'registroInscripciones',
                'ordering': ['-created'],
            },
        ),
    ]
