# Generated by Django 5.0.6 on 2024-07-09 01:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('distancia', models.FloatField()),
                ('Status', models.BooleanField()),
                ('precio', models.FloatField()),
                ('estado', models.CharField(max_length=15)),
                ('ciudad', models.CharField(max_length=15)),
                ('duracion', models.FloatField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='rutas/')),
            ],
            options={
                'verbose_name': 'Ruta',
                'verbose_name_plural': 'Rutas',
            },
        ),
        migrations.CreateModel(
            name='RutaRealizada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_realizacion', models.DateField(auto_now_add=True)),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutarealizada', to='rutas.ruta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'RutaRealizada',
                'verbose_name_plural': 'RutasRealizadas',
            },
        ),
    ]
