# Generated by Django 5.0.6 on 2024-07-10 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rutarealizada',
            name='fecha_realizacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
