# Generated by Django 5.0.6 on 2024-08-12 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0002_remove_rutarealizada_fecha_realizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruta',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
    ]
