# Generated by Django 5.0.6 on 2024-08-16 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0003_ruta_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruta',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
